[package]
name = "minecraft-binary-search-helper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zip = "0.6.3"
toml = "0.5.9"
serde = "1.0.147"
serde_derive = "1.0.147"

petgraph = "0.6.2"